### ISSUE TITLE
`deinit()` for picodisplay?

### ISSUE THREAD

**Issue by teuler** [pimoroni/pimoroni-pico#120]
... it would be great if one could release all the resources (i.e. the memory buffer) that is used by the picodisplay.

**Comment by Gadgetoid** [comment]
Interesting- what's the use case?

This would be implicitly supported if we converted all of our module type libraries into classes, and I think we should probably do that at some point, there's an issue to track this idea (more generally) https://github.com/pimoroni/pimoroni-pico/issues/197

It's useful at least in MicroPython since it stops resource leaks over soft resets.

**Comment by Gadgetoid** [comment]
May happen as part of #309
