### ISSUE TITLE
Provide MicroPython stubs for frozen libraries

### ISSUE THREAD

**Issue by aivarannamaa** [pimoroni/pimoroni-pico#178]
It would be nice if there was something like https://pypi.org/project/circuitpython-stubs for Pimoroni Pico libs, which could be used for code completion, linting etc.

**Comment by arunura** [comment]
+1

**Comment by Gadgetoid** [comment]
I looked at introspecting the raw .c files to gather information for stubs, but it's no trivial problem. I did some preliminary digging into stubber mentioned in #742, but since our C++ libraries have *largely* static APIs it seems like it might just be easier to hand-write them all than get buried in tooling hell.

As such I've started a stubs repository here https://github.com/pimoroni/pimoroni-pico-stubs

I need to figure out how to make this installable and - of course - add all the many, many missing modules.
