### ISSUE TITLE
Badger 2040 - more readable sans font?

### ISSUE THREAD

**Issue by toyg** [pimoroni/pimoroni-pico#281]
It's somewhat incongruous that a low-resolution device has more serif options than sans-serif ones. It should probably have one low-res-optimized typeface, i.e. a proper "pixel font". 

As it is, all sans text looks like Comic Sans, with all that it entails (I'm sure the OpenBSD crowd is very happy, but...).

**Comment by Gadgetoid** [comment]
Progress:

![image](https://user-images.githubusercontent.com/1746967/160639512-b48b2cda-41d0-4c8b-b316-099bf0f0044b.png)

**Comment by Gadgetoid** [comment]
Bitmap fonts "bitmap6" and "bitmap8" are now available in a pre-release build here (must be logged into GitHub) - https://github.com/pimoroni/pimoroni-pico/actions/runs/2065394844

Scale must be an integer >= 1, and text is - slightly frustratingly - orientated from its top left corner. Otherwise it should work more or less the same as the vector fonts.

Will be in v1.18.6 this Friday!

**Comment by helgibbons** [comment]
I've just updated the Badger docs (#337) to include the info above so I think we should be good to close this now?
