### ISSUE TITLE
ST7789 display connect to custom pins

### ISSUE THREAD

**Issue by AlexeyPechnikov** [pimoroni/pimoroni-pico#384]
I'm trying v1.18.8 to use ST7789 with custom pins:

<img width="170" alt="image" src="https://user-images.githubusercontent.com/7342379/172697390-79f05e00-219c-4e20-b5db-5c5d06c1363d.png">

but it doesn't work:

```
import st7789
st7789.ST7789(135, 240, rotate180=False, slot=0, cs=5, dc=1)

> ST7789(spi = 0, cs = 17, dc = 16, sck = 18, mosi = 19, bl = 20)
```

Is it possible to use all the custom display connection pins for the driver? I think 'slot' variable is not documented, right?

Also, 'cs' and 'dc' arguments looks weird because we can't use machine.Pin() instances here:

```
st7789.ST7789(135, 240, rotate180=False, slot=0, cs=machine.Pin(5), dc=machine.Pin(1))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert Pin to int
```

so it's not clear if GP0 is equal to 0 or 1 here. Anyway, these arguments don't work and we have no ability to define backlight pin and so on.

**Comment by Gadgetoid** [comment]
This will all change with #373 and I definitely recommend giving those builds a try if you're using a display.

**Comment by Gadgetoid** [comment]
In your case you will be wanting something like:

```python
from pimoroni_bus import SPIBus
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_RGB565

spibus = SPIBus(cs=5, dc=1, sck=2, mosi=3, bl=4)

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, bus=spibus, pen_type=PEN_RGB565)
```

And a bleeding edge build like https://github.com/pimoroni/pimoroni-pico/actions/runs/2462877886 or later.

If you want to half your RAM usage and just use 256 colours you can use `PEN_RGB332`. Handy if you want multiple displays.

**Comment by mobigroup** [comment]
Ah, thanks! It works for rotate=0 but not for rotate=90:
```
from pimoroni_bus import SPIBus
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_RGB565

spibus = SPIBus(cs=5, dc=1, sck=2, mosi=3, bl=4)
display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, bus=spibus, pen_type=PEN_RGB565, rotate=90)
```
Please see the picture below where the rotated display filled by random coloured points at bottom line (due to uninitialised or too small frame buffer, I suppose):
![IMG_0904](https://user-images.githubusercontent.com/7342379/172872616-dfec7ee9-9322-4092-9c4b-e64954c14b9d.jpg)

**Comment by Gadgetoid** [comment]
Ha, I thought I'd tested them all. I'll add this to my TODO!

**Comment by mobigroup** [comment]
Hmm, for Pico Display V2 I see the same small picture on the display for the both rotate=0 and rotate=90:
```
spibus = SPIBus(cs=17, dc=16, sck=18, mosi=19)

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, bus=spibus, pen_type=PEN_RGB565, rotate=0)
```
![IMG_0905](https://user-images.githubusercontent.com/7342379/172876864-4a78c578-bf28-487a-8c20-425aac836a7d.jpg)

**Comment by Gadgetoid** [comment]
Change `DISPLAY_PICO_DISPLAY` in your code to `DISPLAY_PICO_DISPLAY_2`

**Comment by mobigroup** [comment]
Yes, it works with display=DISPLAY_PICO_DISPLAY_2 but how about different display sizes?

**Comment by Gadgetoid** [comment]
They were never supported in the first place- supplying width/height was more a nuisance than a feature since unsupported values would break or be ignored.

**Comment by Gadgetoid** [comment]
Sort of- the buffer size didn't really *do* anything useful. If it's too small you'd get an error, and if it's too large you'd waste RAM.

The whole `display.init(buffer)` thing was a workaround for our lack of understanding about how MicroPython worked :laughing:

You can still supply a custom buffer using the `buffer` argument in PicoGraphics, but there's no real purpose to that.

Supporting different screen resolutions must be done in the underlying driver itself. That's done pretty naively by a hard-coded table of values that work with our products:

https://github.com/pimoroni/pimoroni-pico/blob/b41631bc14953453d2719592640adde8437f6d12/drivers/st7789/st7789.cpp#L100-L150

(Though this has since been somewhat rewritten)

**Comment by mobigroup** [comment]
Ok, got it. Anyway, please save ability to change the driver for the display wrapper ("picographics") for your future products (maybe touch screen-enabled ones)! It looks as you are going to hide too deep all the details about st7789 driver...

P.S. At the end of the day I think it doesn't look user friendly to disable usage of other [larger] screens! Why should we look for other library and adopt our codes when we buy additional displays on the same driver? It'd be great to use "picographics" for any screen [using many drivers ;)].

**Comment by Gadgetoid** [comment]
Supporting other screens would be nice, but I need:

1. Time
2. The screens to test with

Ignoring all the MicroPython veneer over the top, PicoGraphics and the display drivers are quite separate- in fact "PicoGraphics" as presented to MicroPython already transparently supports both ST7789 and ST7735 based displays with more to come.

**Comment by mobigroup** [comment]
Yes, sure. picographics library looks great, thanks! I just worry if we will be able to use it smoothly in the future. For an example, it’d be nice to have some touchscreen display for Pico like to pair of touch controller XPT2046 plus ILI9488 driver for 480x320 display.

**Comment by Gadgetoid** [comment]
Closing as complete. I think there are enough supported display types now to set a pretty good example for how supporting another one might be accomplished. And you can `memoryview(picographics)` to get to the raw buffer and copy it over with your own Python driver if you're so inclined.

I can't merge support for anything we don't make because flash storage is getting *really tight* on particularly the Pico W and, long term, more things will probably have to be done in pure Python anyway.
