### ISSUE TITLE
Typos in example code for pico_display

### ISSUE THREAD

**Issue by Pinkyatacme** [pimoroni/pimoroni-pico#40]
Typos in the README.md example code result in a failure to compile.
Line 54: 'rect' should be 'Rect'
Line 60: 'point' should be 'Point'

**Comment by martintsw** [comment]
...And the call to set_pen changing the colour to something different that was used earlier for the text_rect so that the text is actually visible is missing from the code.
_eg_ add a pico_display.set_pen( 196, 145, 2 ); immediately preceding the pico_display.set_pen( 196, 145, 2 ); and the example actually works (along with the name capitalization changes others have noted).

**Comment by Pinkyatacme** [comment]
Fixed in PR #42
