### ISSUE TITLE
picoexplorer.get_adc(x) hangs

### ISSUE THREAD

**Issue by lowfatcode** [pimoroni/pimoroni-pico#52]
When attempting to read an ADC channel from Micro Python the Pico hangs completely.

**Comment by lesp** [comment]
Thonny shell becomes unresponsive, and I have to power off the Pico to regain shell.

![Screenshot from 2021-02-10 18-02-17](https://user-images.githubusercontent.com/998860/107553121-46304100-6bcc-11eb-9730-d538e82582f7.png)

**Comment by UnfinishedStuff** [comment]
After a bit of poking, this seems to happen if you don't call `picoexplorer.init()` first.  You need to pass `init()` a bytearray, but if you're not using the screen it can be an empty array.

Presumably this is because `init` also initialises the ADCs.

**Comment by ZodiusInfuser** [comment]
Thanks for pointing this out @lesp! As @UnfinishedStuff mentions, the cause of the problem is that you're not calling `picoexplorer.init(<bytearray>)` before you attempt to read the ADC, which means an instance of PicoExplorer does not exist at that point.

This is something we should be handling gracefully, so what I'll do is have each function fire off a RuntimeException in this case that will instruct the user that init needs to be called, like:

![image](https://user-images.githubusercontent.com/7437269/107637054-7841b180-6c65-11eb-8973-74096460efd8.png)

Quick question though. How should I do the wording for that error message?

**Comment by ZodiusInfuser** [comment]
#54
