### ISSUE TITLE
Plasma - problems with v1.19.12

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/pimoroni-pico#637]
See https://forums.pimoroni.com/t/wireless-plasma-kit-issues/21274

I'm getting no lights and hard locks in Thonny when trying to init the LEDs with a Plasma Stick running v1.19.12 MicroPython firmware.

Works fine if I flash the board with v1.19.11.

**Comment by helgibbons** [comment]
Just tried v1.19.12 on a Plasma 2040 (and a different computer, to rule out Thonny shenanigans!) and that's also not working.

**Comment by Gadgetoid** [comment]
I expected *something* would break, since we moved through a few months of MicroPython updates in a single point release :grimacing: 

Frustratingly Plasma had already been optimized to the nth degree for similar problems before, so none of the usual suspects are the problem here.

It doesn't seem to be related to the PIO or State Machine choices, since it freezes with any configuration for me.

And, even weirder, if I supply a buffer that's under-sized it *still* freezes.

It *should* be bailing with a ValueError: https://github.com/pimoroni/pimoroni-pico/blob/b3edbc47d085ceb8fe7b8ec377a23b87ddb494bb/micropython/modules/plasma/plasma.cpp#L93

At this point it hasn't done anything particularly onerous!

**Comment by Gadgetoid** [comment]
Even stranger, this hard-locks:

```python
>>> import plasma
>>> plasma.WS2812()
```

The first four args are *required* so this should bail in argument parsing. Something must be wrong with the linkage into the C module

IE: The new `MP_DEFINE_CONST_OBJ_TYPE` macro must have the wrong function set for the class constructor.

**Comment by Gadgetoid** [comment]
I don't know whether to laugh or cry:

```c
MP_DEFINE_CONST_OBJ_TYPE(
    PlasmaWS2812_type,
    MP_QSTR_plasma_ws2812,
    MP_TYPE_FLAG_NONE,
    make_new, PlasmaWS2812_print,
    print, PlasmaWS2812_make_new,
    locals_dict, (mp_obj_dict_t*)&PlasmaWS2812_locals_dict
);
```
